# Generated by Django 2.0 on 2022-09-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('number', models.BigIntegerField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('sal', models.CharField(max_length=20)),
            ],
        ),
    ]
