# Generated by Django 2.0 on 2022-09-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
