# Generated by Django 3.2.15 on 2022-10-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0003_alter_employee_data_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_data',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='employee_data',
            old_name='ename',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee_data',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee_data',
            old_name='number',
            new_name='mobile_number',
        ),
        migrations.RenameField(
            model_name='employee_data',
            old_name='sal',
            new_name='salary',
        ),
    ]
