# Generated by Django 3.2.15 on 2022-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curdapp', '0004_auto_20221002_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_data',
            name='email_id',
            field=models.EmailField(max_length=100),
        ),
    ]
